on:
  push:
    branches:
      - "feature/**"

name: dev
env:
  ENV: dev

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        name: Setup Go
        with:
          go-version-file: "code/go.mod"
      - run: go build -o main ./cmd/lambda/
        name: Build GO lambda project
        working-directory: ./code
      - run: zip -qq -r function.zip main configs/
        working-directory: ./code
