on:
  push:
    branches:
      - "feature/**"

name: dev
env:
  ENV: dev
  LAMBDA_FUNCTION_NAME: image-scaling-trigger

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        name: Setup Go
        with:
          go-version-file: "code/go.mod"
          cache: true
          cache-dependency-path: code/go.sum
      - run: CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/lambda/
        name: Build GO lambda project
        working-directory: ./code
      - run: zip -qq -r function.zip main configs/
        working-directory: ./code
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lambda-go-zip
          path: code/function.zip
  deploy:
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: lambda-go-zip
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to AWS lambda
        run: |
          echo "::set-output name=VERSION_ID::$(aws lambda update-function-code --function-name ${{env.LAMBDA_FUNCTION_NAME}} --zip-file fileb://function.zip --publish | jq -r .Version)"
        id: lambda_version
      - name: Update Lambda alias
        run: aws lambda update-alias --function-name ${{env.LAMBDA_FUNCTION_NAME}} --function-version ${{steps.lambda_version.outputs.VERSION_ID}} --name ${ENV}
