on:
  push:
    branches:
      - "feature/**"

name: dev
env:
  ENV: dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        name: Setup Go
        with:
          go-version-file: "code/go.mod"
      - run: go build -o main ./cmd/lambda/
        name: Build GO lambda project
        working-directory: ./code
      - uses: montudor/action-zip@v1
        name: Zip Go artifact
        with:
          args: zip -qq -r function.zip main configs/
