name: dev

on:
  push:
    branches:
      - "feature/**"
    paths:
      - code/**
      - .github/workflows/reusable-workflow.yaml
      - .github/workflows/dev-workflow.yaml
jobs:
  dev:
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      ENV: "dev"
      LAMBDA_FUNCTION_NAME: "image-scaling-trigger-dev"
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{secrets.AWS_REGION}}
