name: prod

on:
  push:
    branches:
      - "main"
    tags:
      - release-*

jobs:
  prod:
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      ENV: "prod"
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{secrets.AWS_REGION}}
